### ISSUE TITLE
CMake warning when using with CMake >= 3.0

### ISSUE THREAD

**Issue by Kicer86** [ErwanLegrand/libbacktrace#2]
CMake Warning (dev) at CMakeLists.txt:34 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

**Comment by ErwanLegrand** [comment]
Thanks! The last commit should fix this.

**Comment by Kicer86** [comment]
I think something like "cmake_policy(SET CMP0048 OLD)" should be used
